import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Wrapper from "@/components/Wrapper";
import { QueryClient, QueryClientProvider } from "react-query";
import QueryClientWrapper from "@/components/QueryClient";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  bg-[#030637] mt-28` }>
        <QueryClientWrapper>
          <Header />
          <Wrapper className="py-10">
          {children}
          </Wrapper>
        </QueryClientWrapper>
      </body>
    </html>
  );
}
